//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MvcStock.Models.Entity
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class TblSale
    {
        [Required(ErrorMessage = "Lütfen bu alaný doldurunuz.")]
        public int Sale { get; set; }
        [Required(ErrorMessage = "Lütfen bu alaný doldurunuz.")]

        public int Product { get; set; }
        [Required(ErrorMessage = "Lütfen bu alaný doldurunuz.")]

        public int Customer { get; set; }
        [Required(ErrorMessage = "Lütfen bu alaný doldurunuz.")]
        public byte Total { get; set; }
        [Required(ErrorMessage = "Lütfen bu alaný doldurunuz.")]
        public decimal Price { get; set; }

        public virtual TblCustomer TblCustomer { get; set; }
        public virtual TblProduct TblProduct { get; set; }
    }
}
